py2 LazyDB/FilesDB: Use pickle protocol v2, write gdbm-backed shelve, set FILESDB_FORMAT_VERSION = 3
getsolus/eopkg pull request #86
Opened 2024-09-24 20:07 UTC by joebonrichie

The goal is to prototype auto-regeneration of a gdbm backed shelve in eopkg.py2.

Once we're happy with the logic, we can implement similar logic for eopkg.py3 (see #89), thus enabling us to switch back and forth between versions and having the FilesDB cache auto-regenerated on demand.

eopkg.py2 sets `pisi/db/filesdb.FILESDB_FORMAT_VERSION = 3` manually.

**Test Plan**

Non-root `./eopkg.py2` behaviour:
1. _No FilesDB_: `sudo rm /var/lib/eopkg/info/files.db* ; time ./eopkg.py2 -d sf /bin/bash`
1. _Empty FilesDB_: `sudo touch /var/lib/eopkg/info/files.db && time ./eopkg.py2 -d sf /bin/bash`
1. _Corrupt FilesDB_: `sync && echo "0xDEADBEEF" | sudo tee /var/lib/eopkg/info/files.db && sync && time ./eopkg.py2 -d sf /bin/bash`
1. _Unversioned bsddb FilesDB_: `sudo rm /var/lib/eopkg/info/files.db* ; sync && time sudo eopkg.py2 -dy rdb && sync && time ./eopkg.py2 -d sf /bin/bash` 

Root `./eopkg.py2` behaviour:
1. _Rebuild FilesDB_: `sync && time sudo ./eopkg.py2 -dy rdb`
1. _No FilesDB_: ` sync && sudo rm /var/lib/eopkg/info/files.db* ; time sudo ./eopkg.py2 -d sf /bin/bash && time sudo ./eopkg.py2 -d sf /bin/bash`
1. _Empty FilesDB_: `sync && sudo rm /var/lib/eopkg/info/files.db* ; sudo touch /var/lib/eopkg/info/files.db && time sudo ./eopkg.py2 -d sf /bin/bash && sync && time sudo ./eopkg.py2 -d sf /bin/bash` 
1. _Corrupt FilesDB_: `sync && echo "0xDEADBEEF" | sudo tee /var/lib/eopkg/info/files.db && sync && time sudo ./eopkg.py2 -d sf /bin/bash && sync && time sudo ./eopkg.py2 -d sf /bin/bash`
1. _Unversionved bsddb FilesDB_: `sync && sudo rm /var/lib/eopkg/info/files.db* ; sync && time sudo eopkg.py2 -dy rdb && sync && time sudo ./eopkg.py2 -d sf /bin/bash && sync && time sudo ./eopkg.py2 -d sf /bin/bash`

**NB**: All instances of `sudo eopkg.py2 -dy rdb` are quite deliberate; we want the old version of eopkg.py2 to generate a bsddb format FilesDB db, so we can see what happens and whether it gets regenerated as it is supposed to when we run the present PR code against it.

Land _before_ #89

2024-10-03 20:02 UTC, silkeh requested changes
Version is not correct (my fault), otherwise LGTM!

2024-10-03 20:02 UTC, silkeh commented on README.md
> +From version 3.12.4, eopkg.py2 will be using a FILESDB_FORMAT_VERSION = 3 versioned gdbm format
```suggestion
From version 3.12.5, eopkg.py2 will be using a FILESDB_FORMAT_VERSION = 3 versioned gdbm format
```

2024-10-03 20:02 UTC, silkeh commented on README.md
> +This implies that from version 3.12.4 and forward, eopkg.py2 will need to be built with gdbm support, but no
```suggestion
This implies that from version 3.12.5 and forward, eopkg.py2 will need to be built with gdbm support, but no
```

2024-10-03 20:02 UTC, silkeh commented on pisi/__init__.py
> +__version__ = "3.12.4"
```suggestion
__version__ = "3.12.5"
```

2024-10-04 03:54 UTC, sheepman4267 commented
So, I'm not sure what's going on here. The documented test plan here seems to work, but unfortunately running `sudo ./eopkg.py2 rdb` does not. It *looks* like it finishes rebuilding the DB (maybe), but then dies like this at the end:

```
Adding 'sqlite3-devel' to db... DEBUG: InstallDB initialized in 0.00866103172302.
No handlers could be found for logger "pisi"
System error. Program terminated.
<type 'exceptions.AttributeError'>: installed_db
Please use 'eopkg help' for general help.

Traceback:
  File "./eopkg.py2", line 78, in <module>
    cli.run_command()
  File "/home/sheepman/Solus/eopkg/pisi/cli/pisicli.py", line 138, in run_command
    self.command.run()
  File "/home/sheepman/Solus/eopkg/pisi/cli/rebuilddb.py", line 50, in run
    pisi.api.rebuild_db(ctx.get_option('files'))
  File "/home/sheepman/Solus/eopkg/pisi/api.py", line 65, in wrapper
    ret = func(*__args,**__kw)
  File "/home/sheepman/Solus/eopkg/pisi/api.py", line 855, in rebuild_db
    rebuild_filesdb()
  File "/home/sheepman/Solus/eopkg/pisi/api.py", line 834, in rebuild_filesdb
    files = installdb.get_files(pkg)
  File "/home/sheepman/Solus/eopkg/pisi/db/installdb.py", line 161, in get_files
    files_xml = os.path.join(self.package_path(package), ctx.const.files_xml)
  File "/home/sheepman/Solus/eopkg/pisi/db/installdb.py", line 355, in package_path
    if self.installed_db.has_key(package):
  File "/home/sheepman/Solus/eopkg/pisi/db/lazydb.py", line 127, in __getattr__
    raise AttributeError, attr
```
I tried for about half an hour to root-cause this, but don't have a lot of brain-power tonight. The fault doesn't immediately seem to come from changes made in the PR, and I think PiSi doesn't quite print debug messages in order. Makes instrumenting this really, really annoying...

2024-10-04 09:00 UTC, silkeh commented
@sheepman4267 does that also happen on the `python2` branch?

2024-10-04 11:03 UTC, ermo commented
@sheepman4267 First of all, thank you for being diligent enough to think of testing the `rdb` command.

Looking at the trace with my knowledge of the code, the order of operations looks legit.

This clearly needs fixing. I have an idea for how to refactor this so it's less spaghetti, and so the order of operations are saner.

It should essentially make `rdb` nicer in terms of its call chain and move the responsibility for the why, the when and the how of the rebuild fully into the FilesDB class.

2024-10-04 11:04 UTC, ermo commented
> @sheepman4267 does that also happen on the `python2` branch?

It doesn't for me.

2024-10-06 14:57 UTC, silkeh approved these changes
That if/else tree is a bit too deep for my comfort, but I'll allow it. We can always clean it up later when we got rid of the py2 version.

Test plan works like a charm and does the expected things.

LGTM!

2024-10-06 22:37 UTC, sheepman4267 approved these changes
I agree with @silkeh, that if/else tree is really something. It works, though, so let's run with it for now. I'll do more splitting of those hairs when we come to the py3 stuff. 

Thank you for slogging through this mess!

2024-10-06 22:47 UTC, merged